GROUND_BALL = "Ground Ball"
LINE_DRIVE = "Line Drive"
FLY_BALL = "Fly Ball"
SINGLE = "Single"
DOUBLE = "Double"
TRIPLE = "Triple"
HOME_RUN = "Home Run"
STRIKEOUT = "Strikeout"
GROUND_OUT = "Ground out"
LINE_OUT = "Line out"
FLY_OUT = "Fly out"
FIRST_BASE = 0
SECOND_BASE = 1
THIRD_BASE = 2
